# Generated by Django 2.2 on 2019-05-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190424_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ranked_solo',
            new_name='ranked_solo_points',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranked_solo_rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranked_solo_tier',
            field=models.CharField(default='', max_length=100),
        ),
    ]
