# Generated by Django 2.2 on 2019-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190518_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ranked_flex',
            field=models.CharField(default='Not set yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranked_solo_points',
            field=models.CharField(default='Not set yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranked_solo_rank',
            field=models.CharField(default='Not set yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranked_solo_tier',
            field=models.CharField(default='Not set yet', max_length=100),
        ),
    ]
