# Generated by Django 2.2 on 2019-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190518_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ranked_solo_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ranked_solo_rank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ranked_solo_tier',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranked_solo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranked_flex',
            field=models.CharField(default='', max_length=100),
        ),
    ]
