# Generated by Django 2.2 on 2019-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190607_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='country',
        ),
    ]
