# Generated by Django 2.2 on 2019-06-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190608_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='city',
        ),
    ]
