# Generated by Django 2.2 on 2019-06-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20190608_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='country',
        ),
    ]
